### ISSUE TITLE
Encryption Key - Hash issue

### ISSUE THREAD

**Issue by erikleirdal** [PayEx/Woocommerce-modules#1]
Hi. Trying to use this module, going trough shopping cart trying to pay, it reports to be an hash issue suggesting wrong encryption key. The encryption key works with another payex installation. Hash Algorithm used is MD5.

**Comment by aait** [comment]
Thanks for your feedback Will check this and get back to you early next week. Which payment method are you using?

**Comment by erikleirdal** [comment]
We tested with creditcard. 


/Erik

-------- Opprinnelig melding --------
Fra: aait <notifications@github.com> 
Dato: 2015.08.28  11.16  (GMT+01:00) 
Til: PayEx/Woocommerce-modules <Woocommerce-modules@noreply.github.com> 
Ko: erikleirdal <erik@leirdal.no> 
Emne: Re: [Woocommerce-modules] Encryption Key - Hash issue (#1) 

Thanks for your feedback Will check this and get back to you early next week. Which payment method are you using?

**Comment by aait** [comment]
Hi Erik,

It works here. Which module version are you using?


Mvh
Richard Birnik - AAIT - +46 (0)8- 5016 7710

**Comment by erikleirdal** [comment]
Hello Richard,

Versjon 2.0.0pre

/Erik
Den 01.09.2015 11.32, skrev aait:

**Comment by aait** [comment]
Are you using live or test account? If yo uare using live, have you set the correct IP in the IP-filter?

**Comment by erikleirdal** [comment]
Hello,

Yes we are running live, and we allready use another payex module 
(without the Invoice function, so that is why we want to try your 
module), so yes our IP is configured in PayEx IP filter.

Before I test your PayEx module I simply deactivate the other module. 
Should that be sufficiant?

Med vennlig hilsen
Erik Leirdal
+47 97067001

Den 03-Sep-15 10:34, skrev aait:

**Comment by aait** [comment]
I dont know your other module, but it is very likely you need to delete it, yes. Also, i suggest you to setup a testenvironment while testing.

**Comment by erikleirdal** [comment]
Your PayEx module is now the only one installed, it still show the error 
message "The hash on request is not valid, this might be due to the 
encryption key being incorrect"

Do you have any idea how to troubleshoot this?


Den 03-Sep-15 10:46, skrev aait:

**Comment by aait** [comment]
Have you tried to regenerate the  hash key? Be sure  no hidden signs or space is there. If  it is still persist we're gonna have to access your site and troubleshoot

**Comment by erikleirdal** [comment]
I have'nt tried to do that, but we are simply using the same 
account&encryption key used allready in other working systems (copy-paste)

How should I comunicate a login for you? Through this email?

Den 03-Sep-15 13:43, skrev aait:

**Comment by aait** [comment]
First, please copy paste through for example to ensure no hidden signs are copied by mistake, if it still persist  send details to info@aait.se

**Comment by erikleirdal** [comment]
We tried to generate a new encryption, without any luck.

Useracount crated and details should be sent to your email.


Den 03-Sep-15 13:50, skrev aait:

**Comment by aait** [comment]
have u disabled payex frontend? i dont see the payment methid as an option? also pls send me your email,

**Comment by erikleirdal** [comment]
erik@safemate.no is my corporate email.

Probably because administrator has other settings. let me anable payex 
for administartor.

Med vennlig hilsen
Erik Leirdal
+47 97067001

Den 03-Sep-15 14:21, skrev aait:

**Comment by Cannibal-Llama** [comment]
Any advance on this? I am running into the same problem

**Comment by aait** [comment]
@Cannibal-Llama This issue is solverd. Do you still have problems? With the latest module?

**Comment by aait** [comment]
PayEx API sends wrong error code. WE have noticed this error for example in trailing space in zip.code. On our newst nodule we have not received any problem reports, so we close this issue
