### ISSUE TITLE
WooCommerce/Orders/Refund/Refund via PayEx Payments does not work

### ISSUE THREAD

**Issue by pxsimon** [PayEx/Woocommerce-modules#11]
Making a refund via WooCommerce backend towards PayEx does not work, generates an error and PayEx receives no request.

However a notification might be sent to the end-customer.

**Comment by aait** [comment]
Fixed in https://github.com/PayEx/Woocommerce-modules/commit/f34737e7cd3187857696a06ffa22fb921d71f33d
