### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by gabrielwinnberg** [PayEx/Woocommerce-modules#14]
Hello,

I just got this error message:

Warning: Creating default object from empty value in /home/u/u1089771/www/ng-wp/wp-content/plugins/woocommerce-gateway-payex-payment/plugin-update-checker/plugin-update-checker.php on line 227

Cheers,
Gabriel

**Comment by aait** [comment]
It was a problem with the update server. It's now fixed.

**Comment by asbjornu** [comment]
@aait A failing update check shouldn't break anything, agree? A `try/catch` around that part would be nice.

**Comment by aait** [comment]
It's a php-warning (nothing brakes). Try/catch doesnt catch warnings unfortunately. Merchant can set error_reporting(0) in php-config to prevent warnings.

**Comment by asbjornu** [comment]
:+1:
