### ISSUE TITLE
PayEx error: ValidationError

### ISSUE THREAD

**Issue by erikleirdal** [PayEx/Woocommerce-modules#2]
Hi. I beleive this error came after yesterdays update??

  "PayEx error: ValidationError_InvalidParameter (Invalid parameter:countryCode, value:null Parameter name: countryCode)".

At least, it worked before yesterday, however, today I'm getting this error.

**Comment by aait** [comment]
This is an interesting problem. Did you change country on the billing address?

**Comment by erikleirdal** [comment]
Country has not changed, its been Norway all the time. 


/Erik

-------- Opprinnelig melding --------
Fra: aait <notifications@github.com> 
Dato: 2015.09.28  15.09  (GMT+01:00) 
Til: PayEx/Woocommerce-modules <Woocommerce-modules@noreply.github.com> 
Ko: erikleirdal <erik@leirdal.no> 
Emne: Re: [Woocommerce-modules] PayEx error: ValidationError (#2) 

This is an interesting problem. Did you change country on the billing address?

**Comment by aait** [comment]
OK please mail me the exact order and I will have a look at it.
