### ISSUE TITLE
Avoid Question "Corporate Organization Number" on every order

### ISSUE THREAD

**Issue by erikleirdal** [PayEx/Woocommerce-modules#3]
1. We dont offer Invoice for private
2. We only allow invoice to pre-aprooved companies.

Can we store the company organization number on the customer/user record, having payex module to use this every time, avoiding asking for the organization number on ever order?

Can we buy such modification service from you, or can we invite other woocommerce freelancers to work on the code?

**Comment by aait** [comment]
Hi Erik,

PayEx Financing Invoice doesn't support corporations at this stage. Please see PayEx Ledger service. I sent you a mail with further info.
