### ISSUE TITLE
Remove Invoice 2.0 Factoring

### ISSUE THREAD

**Issue by aait** [PayEx/Woocommerce-modules#5]
This option should not be present anymore.

**Comment by aait** [comment]
Removed.

**Comment by asbjornu** [comment]
@aait Where was it removed? In which commit?

**Comment by aait** [comment]
https://github.com/PayEx/Woocommerce-modules/commit/c9d819c15481fad0babb8a5534f6e2ae643024e4

**Comment by asbjornu** [comment]
@aait It would be great if you could write `Fixes #5` in the commit message, so it is linked up to the issue it resolves. That will also automatically close the issue.

**Comment by aait** [comment]
It was an old commit, but yes, you are right.

**Comment by asbjornu** [comment]
@aait Ah, I didn't notice the old date of the commit. Great! :)
