### ISSUE TITLE
GetAddressByPaymentMethod does not send zipCode

### ISSUE THREAD

**Issue by PayExBent** [PayEx/Woocommerce-modules#6]
`GetAddressByPaymentMethod` requires SSN and zipCode, however the zipCode that the end user provides is not sent in the request.

**Comment by aait** [comment]
Are you sure client dont use old version?
See https://github.com/PayEx/Woocommerce-modules/commit/e12566d3f56d7b5ebfee7e61c2db0f21f4d8d21a#diff-cda550b55684c351baacf628c30e9734R240

**Comment by PayExBent** [comment]
Confirmed that client was using old version, closing issue.
